name: deb

on:
  push:
    branches: ["main"]
    tags:
      - "*"
  pull_request:
    branches: ["main"]

concurrency:
  group: deb-${{ github.sha }}
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build-and-release:
    name: "build and release ${{ matrix.package }} ${{ matrix.arch }} deb"
    strategy:
      matrix:
        package: [smith-updater]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            os: ubuntu-22.04
          - arch: arm64
            os: [self-hosted, linux, arm64, aws, ec2, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Package
        uses: ./.github/actions/build-rust-deb-package
        with:
          package-name: ${{ matrix.package }}

      - name: Release to Teton APT Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: curl -F package=@${{ env.PACKAGE_FILE }} https://${{ secrets.FURY_TOKEN }}@push.fury.io/teton/
