name: test
on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust Toolchain via rust-toolchain.toml
        uses: dsherret/rust-toolchain-file@v1

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true

      - name: Install libdbus-1-dev and pkg-config
        run: sudo apt install libdbus-1-dev pkg-config

      - name: SQLx offline
        run: echo "SQLX_OFFLINE=true" > .env

      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check SQLx
        working-directory: api
        run: cargo sqlx prepare --check

      - name: Run tests
        run: cargo test --workspace

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SMITH_TEAM_SLACK_NOTIFICATIONS }}
